// Measures what a download holds in memory while it transfers a large file, and that what it
// writes is the file, through the transfer the app uses (src/main/downloads/transfer.ts) and the
// real file system. The file is generated by a server in another process, so its bytes never
// count here: a few gigabytes, answered in ranges or whole, and replaced on demand. Cases: a
// ranged transfer to its end; one cancelled midway, which keeps its partial; that partial gone on
// from; a file replaced meanwhile, and a server that ignores ranges, which start again; and a
// disk that fills midway, which leaves a partial and no copy. Prints JSON and, with a path,
// writes it there.
//
//   node apps/desktop/test/e2e/download-memory.ts [size in MiB, 2048] [out.json]
import { fork, type ChildProcess } from "node:child_process";
import { createHash } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdtemp, rm, stat, writeFile } from "node:fs/promises";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Writable } from "node:stream";
import { fileDisk, transfer, type Disk } from "../../src/main/downloads/transfer.ts";

const BLOCK = 1024 * 1024;

/** Block `index` of the file of generation `generation`: the same bytes every time. */
function block(index: number, generation: number): Buffer {
  const bytes = Buffer.allocUnsafe(BLOCK);
  let state = (index * 2654435761 + generation * 40503 + 1) >>> 0;
  for (let at = 0; at < BLOCK; at += 4) {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    bytes.writeUInt32LE(state >>> 0, at);
  }
  return bytes;
}

if (process.argv[2] === "serve") {
  const size = Number(process.argv[3]) * BLOCK;
  let generation = 0;
  let wholeOnly = false;
  const server = createServer((request, response) => {
    if (request.url === "/replace") {
      generation++;
      return response.end("ok");
    }
    if (request.url === "/whole") {
      wholeOnly = true;
      return response.end("ok");
    }
    const range = wholeOnly ? null : /^bytes=(\d+)-$/.exec(request.headers.range ?? "");
    const start = range ? Number(range[1]) : 0;
    const etag = `"file-${generation}"`;
    const ifRange = request.headers["if-range"];
    const ranged = range && (!ifRange || ifRange === etag);
    const from = ranged ? start : 0;
    response.writeHead(ranged ? 206 : 200, {
      "Content-Type": "video/x-matroska",
      "Content-Length": size - from,
      "Accept-Ranges": "bytes",
      ETag: etag,
      ...(ranged ? { "Content-Range": `bytes ${from}-${size - 1}/${size}` } : {}),
    });
    const mine = generation;
    let at = from;
    const send = () => {
      while (at < size) {
        const index = Math.floor(at / BLOCK);
        const piece = block(index, mine).subarray(at - index * BLOCK);
        at += piece.length;
        if (!response.write(piece)) return void response.once("drain", send);
      }
      response.end();
    };
    response.on("close", () => (at = size + 1));
    send();
  });
  server.listen(0, "127.0.0.1", () => {
    const address = server.address();
    process.send?.(typeof address === "object" && address ? address.port : 0);
  });
} else {
  await measure(Number(process.argv[2] ?? 2048), process.argv[3]);
}

async function measure(mebibytes: number, out: string | undefined) {
  const size = mebibytes * BLOCK;
  const server: ChildProcess = fork(import.meta.filename, ["serve", String(mebibytes)], {
    stdio: ["ignore", "inherit", "inherit", "ipc"],
  });
  const port = await new Promise<number>((resolve) =>
    server.once("message", (m) => resolve(Number(m))),
  );
  const origin = `http://127.0.0.1:${port}`;
  const dir = await mkdtemp(join(tmpdir(), "download-memory-"));
  const part = join(dir, "media.mkv.part");
  const results: Record<string, unknown>[] = [];
  const baseline = process.memoryUsage().rss;
  try {
    const run = async (
      name: string,
      known: Parameters<typeof transfer>[0]["known"],
      options: { stopAt?: number; disk?: Disk } = {},
    ) => {
      const stop = new AbortController();
      let peak = process.memoryUsage().rss;
      let peakBuffers = process.memoryUsage().arrayBuffers;
      const sampler = setInterval(() => {
        const usage = process.memoryUsage();
        peak = Math.max(peak, usage.rss);
        peakBuffers = Math.max(peakBuffers, usage.arrayBuffers);
      }, 50);
      let last: { received: number; restarted: boolean; identity: unknown } = {
        received: 0,
        restarted: false,
        identity: null,
      };
      const started = performance.now();
      const outcome = await transfer({
        url: `${origin}/movie.mkv`,
        headers: {},
        request: fetch,
        userAgent: "MrStreamer/measure",
        part,
        known,
        signal: stop.signal,
        disk: options.disk ?? fileDisk,
        progress: (at) => {
          last = at;
          if (options.stopAt !== undefined && at.received >= options.stopAt) stop.abort();
        },
      });
      clearInterval(sampler);
      const seconds = (performance.now() - started) / 1000;
      const onDisk = await stat(part).then(
        (found) => found.size,
        () => 0,
      );
      const result = {
        name,
        outcome: outcome.kind,
        ...(outcome.kind === "failed" ? { failure: outcome.failure } : {}),
        restarted: last.restarted,
        bytesOnDisk: onDisk,
        seconds: Math.round(seconds * 10) / 10,
        mibPerSecond: Math.round((last.received / BLOCK / seconds) * 10) / 10,
        peakRssAboveBaselineMiB: Math.round(((peak - baseline) / BLOCK) * 10) / 10,
        peakArrayBuffersMiB: Math.round((peakBuffers / BLOCK) * 10) / 10,
      };
      results.push(result);
      console.error(JSON.stringify(result));
      return { outcome, last };
    };

    // 1. Ranged, to the end.
    const whole = await run("ranged transfer to the end", null);
    results.at(-1)!["matches"] = await sameAs(part, size, 0);
    await rm(part);
    // 2. Cancelled a third of the way: the partial stays.
    const third = Math.floor(size / 3);
    await run("cancelled a third of the way", null, { stopAt: third });
    // 3. Gone on from that partial under the identity the first answer gave.
    const identity = whole.outcome.kind === "complete" ? whole.outcome.identity : null;
    await run("resumed from the partial", identity);
    results.at(-1)!["matches"] = await sameAs(part, size, 0);
    // 4. Stopped again, then the file replaced: it starts again rather than mixing them.
    await rm(part);
    await run("cancelled before a replacement", null, { stopAt: third });
    await fetch(`${origin}/replace`).then((answer) => answer.text());
    await run("replaced file starts again", identity);
    results.at(-1)!["matches"] = await sameAs(part, size, 1);
    // 5. A server that ignores ranges: the partial is written over from its first byte.
    await rm(part);
    await run("cancelled before ranges stop", null, { stopAt: third });
    await fetch(`${origin}/whole`).then((answer) => answer.text());
    const replacedIdentity = { ...identity!, mark: 'etag "file-1"' };
    await run("range ignored starts again", replacedIdentity);
    results.at(-1)!["matches"] = await sameAs(part, size, 1);
    // 6. A disk that fills a third of the way: failed, with a partial and no copy.
    await rm(part);
    let written = 0;
    const filling: Disk = {
      ...fileDisk,
      write: (path, start) => {
        const file = fileDisk.write(path, start);
        return new Writable({
          write(chunk: Buffer, _encoding, done) {
            written += chunk.length;
            if (written > third) {
              return done(Object.assign(new Error("no space left on device"), { code: "ENOSPC" }));
            }
            if (file.write(chunk)) done();
            else file.once("drain", () => done());
          },
          final(done) {
            file.end(done);
          },
          destroy(error, done) {
            file.destroy();
            done(error);
          },
        });
      },
    };
    await run("disk full a third of the way", null, { disk: filling });
  } finally {
    server.kill();
    await rm(dir, { recursive: true, force: true });
  }
  const report = {
    at: new Date().toISOString(),
    node: process.version,
    platform: `${process.platform}-${process.arch}`,
    fileMiB: mebibytes,
    baselineRssMiB: Math.round((baseline / BLOCK) * 10) / 10,
    results,
  };
  console.log(JSON.stringify(report, null, 2));
  if (out) await writeFile(out, JSON.stringify(report, null, 2));
}

/** Whether the file at `path` is the generated file of `generation`, byte for byte. */
async function sameAs(path: string, size: number, generation: number): Promise<boolean> {
  const expected = createHash("sha256");
  for (let index = 0; index * BLOCK < size; index++) expected.update(block(index, generation));
  const actual = createHash("sha256");
  for await (const chunk of createReadStream(path)) actual.update(chunk as Buffer);
  return expected.digest("hex") === actual.digest("hex");
}
