#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Mac release signing for GitHub Actions: `scripts/setup-release-signing.sh` from a checkout
# where `gh` is signed in with admin access. It stores the team, the notarization key and the
# Developer ID identity as repository settings; docs/maintainers/signing.md explains each one
# and how to renew it. Nothing is written to .env.

TOTAL_STAGES=4

cd "$(git rev-parse --show-toplevel)"
REPO="$(gh repo view --json nameWithOwner --jq .nameWithOwner)"

# has_repo_secret NAME: whether the repository already has an Actions secret NAME.
has_repo_secret() {
  gh secret list --repo "$REPO" --json name --jq '.[].name' 2>/dev/null | grep -qx "$1"
}

banner "Mac release signing for $REPO"

stage "Apple Developer · team"
say "Releases are signed as your paid Apple Developer Program team."
open_url "https://developer.apple.com/account#MembershipDetailsCard"
step "Under Membership details, copy the Team ID: ten capital letters and digits."
ask TEAM_ID "Paste the Team ID:"
until [[ "$TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; do
  warn "A Team ID is ten capital letters and digits."
  ask TEAM_ID "Paste the Team ID:"
done
set_var APPLE_TEAM_ID "$TEAM_ID"
pause "Press Enter to continue."

stage "App Store Connect · notarization key"
say "GitHub Actions notarizes each Mac build with its own API key. The Developer role is enough,"
say "so this key cannot manage users, certificates or apps."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Open Team Keys and click Generate API Key (or +)."
step "Name it, for example \"MrStreamer releases\" (under 30 characters), choose Access: Developer, Generate."
step "Copy the Issuer ID shown above the list, and the new key's Key ID."
step "Download API Key. Apple offers the .p8 file only once; keep it open for the next stage."
ask ISSUER_ID "Paste the Issuer ID:"
until [[ "$ISSUER_ID" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; do
  warn "An Issuer ID is a lowercase UUID."
  ask ISSUER_ID "Paste the Issuer ID:"
done
ask KEY_ID "Paste the Key ID:"
until [[ "$KEY_ID" =~ ^[A-Z0-9]{10}$ ]]; do
  warn "A Key ID is ten capital letters and digits."
  ask KEY_ID "Paste the Key ID:"
done
set_secret APPLE_API_ISSUER "$ISSUER_ID"
set_secret APPLE_API_KEY_ID "$KEY_ID"
pause "Press Enter to continue."

stage "GitHub · store the notarization key"
say "The private key goes straight from your browser into GitHub; nothing secret is typed here."
open_url "https://github.com/$REPO/settings/secrets/actions/new"
step "Name: APPLE_API_KEY_P8"
step "Secret: open AuthKey_${KEY_ID}.p8 in a text editor and paste all of it, BEGIN and END lines included."
step "Click Add secret. To replace an older key, edit APPLE_API_KEY_P8 in the list instead."
pause "Press Enter once it is saved."
until has_repo_secret APPLE_API_KEY_P8; do
  warn "$REPO has no APPLE_API_KEY_P8 secret yet."
  pause "Press Enter to check again."
done
note "  Delete the downloaded .p8 now. If the key is ever lost, revoke it and run this stage again."
pause "Press Enter to continue."

stage "Developer ID · signing identity"
say "GitHub Actions signs with its own Developer ID Application certificate. Its private key is"
say "generated on this machine and stored only in the repository secrets."
if has_repo_secret MAC_CERTIFICATE_P12 && ! confirm "$REPO already has an identity. Replace it?"; then
  say "Keeping the current identity."
else
  node scripts/ci-signing-identity.ts request || true
  step "Only the Account Holder can create Developer ID certificates. Unless Apple issued it above:"
  open_url "https://developer.apple.com/account/resources/certificates/add"
  step "Save the request printed above as mr-streamer-ci.certSigningRequest on your computer."
  step "Choose Developer ID Application, then G2 Sub-CA, upload the request, Continue, Download."
  step "Copy the downloaded .cer to this machine."
  ask CER_PATH "Path of the .cer here (Enter to look it up with ASC_KEY_PATH instead):"
  if [[ -n "$CER_PATH" ]]; then
    node scripts/ci-signing-identity.ts finish --cer "$CER_PATH" || SKIPPED+=("Developer ID identity: node scripts/ci-signing-identity.ts finish --cer FILE")
  else
    node scripts/ci-signing-identity.ts finish || SKIPPED+=("Developer ID identity: node scripts/ci-signing-identity.ts finish")
  fi
fi
note "  Check everything with the Mac signing check workflow: gh workflow run mac-signing-check.yml"
pause "Press Enter to finish."

finish
