#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Microsoft Store setup: the Partner Center steps only Wout can take, from a checkout of the
# repository. The publisher account and the name reservation are done, and the package identity
# lives in the MSIX packaging configuration. docs/maintainers/microsoft-store.md is the runbook.
#
#   scripts/setup-microsoft-store.sh           every stage not done yet, in order
#   scripts/setup-microsoft-store.sh submit    one stage again, by number or name
#   scripts/setup-microsoft-store.sh --list    each stage and whether it's done
#
# Finished stages are recorded in the gitignored .local/microsoft-store-setup.state. Nothing here
# asks for a password, an identity document, a tester's address or any other secret.

cd "$(git rev-parse --show-toplevel)"
STATE_FILE=.local/microsoft-store-setup.state
PARTNER_CENTER=https://aka.ms/submitwindowsapp

STAGES=(notifications testers ready pricing submit)
TITLES=(
  "Partner Center · notification email"
  "Partner Center · testers' group"
  "Private submission · before you start"
  "Private submission · pricing and availability"
  "Private submission · options and submit"
)
TOTAL_STAGES=${#STAGES[@]}

# marked STAGE: print the date STAGE was recorded as done; fails when it wasn't.
marked() {
  local line
  line=$(grep "^$1 " "$STATE_FILE" 2>/dev/null | tail -n1) || return 1
  printf '%s' "${line#* }"
}

# mark STAGE: record STAGE as done today, replacing an earlier record.
mark() {
  local tmp
  tmp=$(mktemp)
  grep -v "^$1 " "$STATE_FILE" > "$tmp" 2>/dev/null || true
  printf '%s %s\n' "$1" "$(date +%F)" >> "$tmp"
  mv "$tmp" "$STATE_FILE"
}

# list_stages: each stage, with the date it was done.
list_stages() {
  local i on
  for i in "${!STAGES[@]}"; do
    if on=$(marked "${STAGES[$i]}"); then on="${GREEN}done $on${RESET}"; else on="to do"; fi
    printf '  %s. %-14s %-48s %s\n' "$((i + 1))" "${STAGES[$i]}" "${TITLES[$i]}" "$on"
  done
}

# run_stage N: show stage N under its own number, even when earlier ones are skipped, then run
# it. Fails when the stage isn't finished, which ends a full run there.
run_stage() {
  _STAGE_INDEX=$1
  stage "${TITLES[$1]}"
  "stage_${STAGES[$1]}"
}

# wrap_up: the closing summary once every stage is done, otherwise what's left.
wrap_up() {
  local name
  for name in "${STAGES[@]}"; do
    if ! marked "$name" >/dev/null; then
      printf '\n'
      list_stages
      printf '\n'
      note "Run scripts/setup-microsoft-store.sh again to continue."
      return
    fi
  done
  finish
  note "Record the submission in the setup record of docs/maintainers/microsoft-store.md."
}

stage_notifications() {
  say "Certification results and required actions arrive by email once Partner Center has"
  say "verified the address it sends them to."
  open_url "https://partner.microsoft.com/dashboard/actioncenter/mypreferences"
  step "In Action Center > My Preferences, verify the email address shown."
  if ! confirm "Is the address verified?"; then
    note "Run scripts/setup-microsoft-store.sh notifications once it is."
    return 1
  fi
  mark notifications
}

stage_testers() {
  say "Only people in a known user group can see and install a private Store app. The"
  say "addresses stay in Partner Center: this wizard never asks for them."
  open_url "https://partner.microsoft.com/dashboard"
  step "Expand Engage in the left menu, click Customer groups, then Create new group."
  step "Name it, for example Mr. Streamer testers, and keep Known user group selected."
  note "  A group can't be renamed or deleted later; its members can change."
  step "Enter each tester's personal Microsoft account address, yours included."
  note "  Work or school accounts can't see or install a private app."
  step "Click Save. Changes to the members can take up to 30 minutes."
  if ! confirm "Is the testers' group saved?"; then
    note "Run scripts/setup-microsoft-store.sh testers once it is."
    return 1
  fi
  mark testers
}

stage_ready() {
  say "The first submission decides for good whether the app can be private, so start it only"
  say "when everything it needs is ready:"
  step "The MSIX the agent built with the Partner Center identity, and its certification kit result."
  step "The listing text, screenshots and logos, and the published privacy policy URL."
  step "Certification notes with a lawful demo provider. Never your own subscription."
  step "Microsoft's answers on HTTP providers and the adult tab, and your decision on what they require."
  step "Your approval of this exact package for the testers."
  if ! confirm "Is all of that ready?"; then
    note "Run scripts/setup-microsoft-store.sh ready when it is."
    return 1
  fi
  mark ready
}

stage_pricing() {
  say "Start the submission and make it private before anything else."
  open_url "$PARTNER_CENTER"
  step "Open Mr. Streamer and click Start submission, or open the draft already there."
  step "Open Pricing and availability."
  step "Under Visibility > Audience, choose Private audience and pick the testers' group."
  warn "Audience defaults to Public audience. Submitted once as public, the app can never be private."
  step "Leave Make this product public on unchecked."
  step "Under Pricing, set Base price to Free and keep No free trial. Keep the default markets."
  step "Click Save."
  if ! confirm "Does Pricing and availability show Private audience, the testers' group and Free?"; then
    note "Nothing is submitted. Run scripts/setup-microsoft-store.sh pricing to try again."
    return 1
  fi
  mark pricing
}

stage_submit() {
  say "Fill in the rest of the draft from what the agent prepared:"
  step "Properties: the Entertainment category and the privacy policy URL."
  step "Age ratings: answer every question honestly, the adult tab included."
  step "Packages: upload the MSIX."
  step "Store listings: the description, which says the app supplies no channels or subscription."
  step "Submission options: under Publishing hold options, choose"
  note "  Don't publish this submission until I select Publish now."
  step "Submission options: paste the prepared text into Notes for certification."
  step "Click Save, then open Pricing and availability once more."
  if ! confirm "Still Private audience and Free, with the publishing hold set?"; then
    note "Nothing is submitted. Fix the draft, then run scripts/setup-microsoft-store.sh submit."
    return 1
  fi
  step "On the overview, click Submit for certification."
  note "  Certification can take up to three business days. Because of the hold, testers get the"
  note "  app only after you click Publish now on the certification status page, and then only"
  note "  the testers' group can see it. Send them the private listing link from Product identity."
  if ! confirm "Is it submitted?"; then
    note "Run scripts/setup-microsoft-store.sh submit when you're ready."
    return 1
  fi
  mark submit
}

case "${1:-}" in
  --list)
    list_stages
    exit 0
    ;;
  -h | --help)
    sed -n '/^# Microsoft Store setup:/,/^# asks for/s/^# \{0,1\}//p' "$0"
    exit 0
    ;;
esac

if ! git check-ignore -q "$STATE_FILE"; then
  printf '%s%s is not gitignored; stopping before writing to it.%s\n' "$RED" "$STATE_FILE" "$RESET" >&2
  exit 1
fi
mkdir -p .local

if [[ -n "${1:-}" ]]; then
  for i in "${!STAGES[@]}"; do
    if [[ "$1" == "$((i + 1))" || "$1" == "${STAGES[$i]}" ]]; then
      run_stage "$i" || true
      wrap_up
      exit 0
    fi
  done
  printf 'No stage %s. The stages:\n' "$1" >&2
  list_stages >&2
  exit 1
fi

banner "Microsoft Store setup for Mr. Streamer"
for i in "${!STAGES[@]}"; do
  marked "${STAGES[$i]}" >/dev/null && continue
  run_stage "$i" || break
done
wrap_up
